---
title: Testing position and rotation
author: Kara Woo
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: github_document
---

```{r knitr-setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE,
                      fig.path = "figs/trig/",
                      fig.align = "center",
                      fig.asp = 1,
                      out.width = "50%")
```

Placement of strip text is incorrect when the text is at angles other than 0,
90, 180, 270. Testing out some ways to improve this.

```{r }
library("ggplot2")
library("grid")
```

```{r }
display_tg <- function(label = "pineapple", ...) {
  tg <- ggplot2:::titleGrob(
                    label,
                    x = NULL,
                    y = NULL,
                    ...,
                    debug = TRUE
                  )
  
  grid.newpage()
  grid.rect()
  ## Draw tg in viewport that is smaller than the page (add_margins doesn't work
  ## for this)
  pushViewport(viewport(w = 0.8, h = 0.8, clip = "off"))
  grid.draw(tg)
}
```

Using [this commit](https://github.com/karawoo/ggplot2/commit/c655de255247feb2bcebb16c421eed37a6f4ca10):

```{r right-angles-just-0}
sapply(c(0, 90, 180, 270), function(x) display_tg(hjust = 0, vjust = 0, angle = x))
```

```{r intermediate-angles-just-0}
sapply(c(45, 135, 225, 315), function(x) display_tg(hjust = 0, vjust = 0, angle = x))
```

```{r intermediate-angles-just-0.5}
sapply(c(45, 135, 225, 315), function(x) display_tg(hjust = 0.5, vjust = 0.5, angle = x))
```

```{r intermediate-angles-just-1}
sapply(c(45, 135, 225, 315), function(x) display_tg(hjust = 1, vjust = 1, angle = x))
```

The above looks about right, but let's check when `hjust` and `vjust` are
different values from one another.

```{r intermediate-angles-just-0-and-1}
sapply(c(45, 135, 225, 315), function(x) display_tg(hjust = 0, vjust = 1, angle = x))
```

```{r intermediate-angles-just-1-and-0}
sapply(c(45, 135, 225, 315), function(x) display_tg(hjust = 1, vjust = 0, angle = x))
```

## Some sample plots:

```{r actual-plots, fig.asp = 0.618, out.width = "80%"}
df <- data.frame(
  x = 1:2,
  y = 1:2,
  z = c("a", "aaaaaaabc"),
  g = c("b", "bbbbbbbcd")
)

base <- ggplot(df, aes(x, y)) + 
  geom_point() +
  facet_grid(g ~ z)

base + 
  theme(
    strip.text.x = element_text(hjust = 0, debug = TRUE),
    strip.text.y = element_text(angle = 45, hjust = 0, debug = TRUE)
  )

base + 
  theme(
    strip.text.x = element_text(angle = 315, debug = TRUE),
    axis.text.x = element_text(angle = -90)
  )
```
